AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    sam-app

    Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 5


Resources:

    CreateBracketFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: create_bracket/
            Handler: create_bracket.lambda_handler
            Runtime: python3.7
            Events:
                CreateBracket:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /api/bracket/create
                        Method: post

Outputs:

    # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
    # Find out more about other implicit resources you can reference within SAM
    # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
    CreateBracketApi:
      Description: "API Gateway endpoint URL for Prod stage for Create Bracket function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/api/bracket/create/"

    CreateBracketFunction:
      Description: "Create Bracket Lambda Function ARN"
      Value: !GetAtt CreateBracketFunction.Arn

    CreateBracketFunctionIamRole:
      Description: "Implicit IAM Role created for Create Bracket function"
      Value: !GetAtt CreateBracketFunctionRole.Arn
