AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    sam-app

    Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 5


Resources:

    CreateResultFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: create_result/
            Handler: create_result.lambda_handler
            Runtime: python3.7
            Events:
                CreateResult:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /api/game/{gameId+}
                        Method: put

Outputs:

    # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
    # Find out more about other implicit resources you can reference within SAM
    # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
    CreateResultApi:
      Description: "API Gateway endpoint URL for Prod stage for Create Result function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/api/game/{gameId+}"

    CreateResultFunction:
      Description: "Create Result Lambda Function ARN"
      Value: !GetAtt CreateResultFunction.Arn

    CreateResultFunctionIamRole:
      Description: "Implicit IAM Role created for Create Result function"
      Value: !GetAtt CreateResultFunctionRole.Arn
