AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    sam-app

    Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 5


Resources:

    GetCognitoUsersFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: get-cognito-users/
            Handler: getCognitoUsers.lambdaHandler
            Runtime: nodejs8.10
            Events:
                GetCognitoUsers:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /api/user/list
                        Method: get

Outputs:

    # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
    # Find out more about other implicit resources you can reference within SAM
    # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
    GetCognitoUsersApi:
      Description: "API Gateway endpoint URL for Prod stage for Get Cognito Users function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/api/user/list/"

    GetCognitoUsersFunction:
      Description: "Get Cognito Users Lambda Function ARN"
      Value: !GetAtt GetCognitoUsersFunction.Arn

    GetCognitoUsersFunctionIamRole:
      Description: "Implicit IAM Role created for Get Cognito Users function"
      Value: !GetAtt GetCognitoUsersFunctionRole.Arn
